import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { BackgroundGlow } from "@/components/BackgroundGlow";
import { NoiseOverlay } from "@/components/NoiseOverlay";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased min-h-screen bg-[--background] text-[--foreground]`}>
        <ThemeProvider>
          <BackgroundGlow />
          <NoiseOverlay />
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
