import type { ThemeTokens } from "@locallaunch/types";

export const themePresets: Record<string, ThemeTokens> = {
  modern: {
    primary: "#6D5EF8",
    secondary: "#0F172A",
    accent: "#A78BFA",
    surface: "#F8FAFC",
    fontHeading: "Inter",
    fontBody: "Inter",
    radius: "rounded",
    animationDensity: "balanced",
  },
  luxury: {
    primary: "#D4AF37",
    secondary: "#111827",
    accent: "#F5E6A8",
    surface: "#09090B",
    fontHeading: "Playfair Display",
    fontBody: "Inter",
    radius: "soft",
    animationDensity: "calm",
  },
  restaurant: {
    primary: "#DC2626",
    secondary: "#1F2937",
    accent: "#FB7185",
    surface: "#FFF7ED",
    fontHeading: "DM Serif Display",
    fontBody: "Inter",
    radius: "rounded",
    animationDensity: "expressive",
  },
  medical: {
    primary: "#0EA5E9",
    secondary: "#0F172A",
    accent: "#22D3EE",
    surface: "#F0F9FF",
    fontHeading: "Inter",
    fontBody: "Inter",
    radius: "soft",
    animationDensity: "calm",
  },
  corporate: {
    primary: "#2563EB",
    secondary: "#111827",
    accent: "#60A5FA",
    surface: "#F9FAFB",
    fontHeading: "Inter",
    fontBody: "Inter",
    radius: "soft",
    animationDensity: "balanced",
  },
  creative: {
    primary: "#EC4899",
    secondary: "#18181B",
    accent: "#8B5CF6",
    surface: "#FAF5FF",
    fontHeading: "Space Grotesk",
    fontBody: "Inter",
    radius: "pill",
    animationDensity: "expressive",
  },
};
